[package]
name = "heroguy_discord_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
lru = "0.14.0"
once_cell = "1.21.3"
serenity = "0.12.4"
sled = "0.34.7"
tokio = { version = "1.45.1", features = ["full"] }
